### PR TITLE
Grammar fixes on Background page

### PR DESCRIPTION
**Pull request by ekcom**
Some grammar fixes and small wording corrections to the background page

### CODE REVIEW

**Comment by angrave** [comment]
Please aalso dd your name to the authors list
https://github.com/illinois-cs241/coursebook/blob/master/AUTHORS.md
and include it to this PR

**Comment by ekcom** [comment]
@angrave done!

**Comment by angrave** [comment]
LGTM

**Comment by angrave** [comment]
@ekcom It takes a while to rebuild but your updates should be live later today -
https://github.com/illinois-cs241/coursebook/actions

**Pull request merged**
